/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RetentionPolicy = IDL.Variant({
  'deleteAfter24h' : IDL.Null,
  'forever' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'retention' : RetentionPolicy,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : UserId,
  'snapId' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'isSnapEvent' : IDL.Bool,
  'receiver' : UserId,
});
export const ContactRequest = IDL.Record({
  'to' : UserId,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'from' : UserId,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Snap = IDL.Record({
  'id' : IDL.Text,
  'opened' : IDL.Bool,
  'sender' : UserId,
  'timestamp' : Time,
  'blobId' : ExternalBlob,
  'receiver' : UserId,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptContactRequest' : IDL.Func([UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationHistory' : IDL.Func([UserId], [IDL.Vec(Message)], ['query']),
  'getUserByPrincipal' : IDL.Func([UserId], [UserProfile], ['query']),
  'getUserByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'findUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Tuple(UserProfile, UserId))], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listContacts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, ContactRequest))],
      ['query'],
    ),
  'listPendingRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(UserId, ContactRequest))],
      ['query'],
    ),
  'listUnopenedSnaps' : IDL.Func([], [IDL.Vec(Snap)], ['query']),
  'openSnap' : IDL.Func([IDL.Text], [ExternalBlob], []),
  'register' : IDL.Func([IDL.Text], [], []),
  'rejectContactRequest' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendContactRequest' : IDL.Func([UserId], [], []),
  'sendMessage' : IDL.Func([UserId, IDL.Text, IDL.Bool], [IDL.Nat], []),
  'sendSnap' : IDL.Func([UserId, ExternalBlob], [IDL.Text], []),
  'updateRetention' : IDL.Func([RetentionPolicy], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RetentionPolicy = IDL.Variant({
    'deleteAfter24h' : IDL.Null,
    'forever' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'retention' : RetentionPolicy,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : UserId,
    'snapId' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'isSnapEvent' : IDL.Bool,
    'receiver' : UserId,
  });
  const ContactRequest = IDL.Record({
    'to' : UserId,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'from' : UserId,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Snap = IDL.Record({
    'id' : IDL.Text,
    'opened' : IDL.Bool,
    'sender' : UserId,
    'timestamp' : Time,
    'blobId' : ExternalBlob,
    'receiver' : UserId,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptContactRequest' : IDL.Func([UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationHistory' : IDL.Func(
        [UserId],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserByPrincipal' : IDL.Func([UserId], [UserProfile], ['query']),
    'getUserByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'findUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Tuple(UserProfile, UserId))], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listContacts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, ContactRequest))],
        ['query'],
      ),
    'listPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(UserId, ContactRequest))],
        ['query'],
      ),
    'listUnopenedSnaps' : IDL.Func([], [IDL.Vec(Snap)], ['query']),
    'openSnap' : IDL.Func([IDL.Text], [ExternalBlob], []),
    'register' : IDL.Func([IDL.Text], [], []),
    'rejectContactRequest' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendContactRequest' : IDL.Func([UserId], [], []),
    'sendMessage' : IDL.Func([UserId, IDL.Text, IDL.Bool], [IDL.Nat], []),
    'sendSnap' : IDL.Func([UserId, ExternalBlob], [IDL.Text], []),
    'updateRetention' : IDL.Func([RetentionPolicy], [], []),
  });
};

export const init = ({ IDL }) => { return []; };