/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactRequest {
  'to' : UserId,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'from' : UserId,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : UserId,
  'snapId' : [] | [string],
  'timestamp' : Time,
  'isSnapEvent' : boolean,
  'receiver' : UserId,
}
export type RetentionPolicy = { 'deleteAfter24h' : null } |
  { 'forever' : null };
export interface Snap {
  'id' : string,
  'opened' : boolean,
  'sender' : UserId,
  'timestamp' : Time,
  'blobId' : ExternalBlob,
  'receiver' : UserId,
}
export type Time = bigint;
export type UserId = Principal;
export interface UserProfile {
  'username' : string,
  'retention' : RetentionPolicy,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptContactRequest' : ActorMethod<[UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'findUserByUsername' : ActorMethod<[string], [] | [[UserProfile, UserId]]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationHistory' : ActorMethod<[UserId], Array<Message>>,
  'getUserByPrincipal' : ActorMethod<[UserId], UserProfile>,
  'getUserByUsername' : ActorMethod<[string], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listContacts' : ActorMethod<[], Array<[UserId, ContactRequest]>>,
  'listPendingRequests' : ActorMethod<[], Array<[UserId, ContactRequest]>>,
  'listUnopenedSnaps' : ActorMethod<[], Array<Snap>>,
  'openSnap' : ActorMethod<[string], ExternalBlob>,
  'register' : ActorMethod<[string], undefined>,
  'rejectContactRequest' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendContactRequest' : ActorMethod<[UserId], undefined>,
  'sendMessage' : ActorMethod<[UserId, string, boolean], bigint>,
  'sendSnap' : ActorMethod<[UserId, ExternalBlob], string>,
  'updateRetention' : ActorMethod<[RetentionPolicy], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];